# li=[1,2,2,3,3,3,4,4,4,4,5,5,5,5,5]
# set1=set(li)
# print(set1)
# res = []
# for i in range(len(li)):
#
#     value=li[i]
#     if value not in res:
#         res.append(value)
#     print(res)
li=[1,2,3,4,5,6,7,8,9]
# list1=li[::-1]
# print(list1)
# rev = []
# print(li[1:-1][::-1])
# for i in li[1:-1:-1]:
#
#     rev.append(i)
# print(rev)

list1=['software engineer','devops','testing']
set1=['Male','Female']
dict1={'seema':22,
       'Anjum':21,
       'Raju':5}
for i in
